# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(400, 293)
        self.buttonBox = QtWidgets.QDialogButtonBox(Welcome)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Welcome)
        self.label.setGeometry(QtCore.QRect(30, 80, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Welcome)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Welcome)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 61, 16))
        self.label_3.setObjectName("label_3")
        self.IPAddress_LineEdit = QtWidgets.QLineEdit(Welcome)
        self.IPAddress_LineEdit.setGeometry(QtCore.QRect(100, 80, 261, 20))
        self.IPAddress_LineEdit.setObjectName("IPAddress_LineEdit")
        self.Port_LineEdit = QtWidgets.QLineEdit(Welcome)
        self.Port_LineEdit.setGeometry(QtCore.QRect(100, 130, 261, 20))
        self.Port_LineEdit.setObjectName("Port_LineEdit")
        self.Nickname_LineEdit = QtWidgets.QLineEdit(Welcome)
        self.Nickname_LineEdit.setGeometry(QtCore.QRect(100, 180, 261, 20))
        self.Nickname_LineEdit.setObjectName("Nickname_LineEdit")
        self.label_4 = QtWidgets.QLabel(Welcome)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 211, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Welcome)

        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "Dialog"))
        self.label.setText(_translate("Welcome", "IP Address:"))
        self.label_2.setText(_translate("Welcome", "Port:"))
        self.label_3.setText(_translate("Welcome", "Nickname:"))
        self.label_4.setText(_translate("Welcome", "Please connect to the server to proceed"))

