# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_client_chat(object):
    def setupUi(self, client_chat):
        client_chat.setObjectName("client_chat")
        client_chat.resize(282, 317)
        self.messageDisplayBrowser = QtWidgets.QTextBrowser(client_chat)
        self.messageDisplayBrowser.setGeometry(QtCore.QRect(10, 30, 261, 192))
        self.messageDisplayBrowser.setObjectName("messageDisplayBrowser")
        self.label = QtWidgets.QLabel(client_chat)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(client_chat)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(client_chat)
        self.lineEdit.setGeometry(QtCore.QRect(10, 230, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.sendButton = QtWidgets.QPushButton(client_chat)
        self.sendButton.setGeometry(QtCore.QRect(190, 230, 81, 31))
        self.sendButton.setObjectName("sendButton")
        self.closeChatButton = QtWidgets.QPushButton(client_chat)
        self.closeChatButton.setGeometry(QtCore.QRect(10, 280, 261, 21))
        self.closeChatButton.setObjectName("closeChatButton")

        self.retranslateUi(client_chat)
        QtCore.QMetaObject.connectSlotsByName(client_chat)

    def retranslateUi(self, client_chat):
        _translate = QtCore.QCoreApplication.translate
        client_chat.setWindowTitle(_translate("client_chat", "Form"))
        self.label.setText(_translate("client_chat", "Chating with:"))
        self.label_2.setText(_translate("client_chat", "[Name]"))
        self.sendButton.setText(_translate("client_chat", "Send"))
        self.closeChatButton.setText(_translate("client_chat", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    client_chat = QtWidgets.QWidget()
    ui = Ui_client_chat()
    ui.setupUi(client_chat)
    client_chat.show()
    sys.exit(app.exec_())
