# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_groupchat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 317)
        self.roomNumberLabel = QtWidgets.QLabel(Form)
        self.roomNumberLabel.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.roomNumberLabel.setObjectName("roomNumberLabel")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 16, 16))
        self.label_5.setObjectName("label_5")
        self.hostLabel = QtWidgets.QLabel(Form)
        self.hostLabel.setGeometry(QtCore.QRect(70, 10, 171, 16))
        self.hostLabel.setObjectName("hostLabel")
        self.MessageBrowser = QtWidgets.QTextBrowser(Form)
        self.MessageBrowser.setGeometry(QtCore.QRect(10, 30, 261, 192))
        self.MessageBrowser.setObjectName("MessageBrowser")
        self.sendMessageLineEdit = QtWidgets.QLineEdit(Form)
        self.sendMessageLineEdit.setGeometry(QtCore.QRect(10, 230, 171, 31))
        self.sendMessageLineEdit.setObjectName("sendMessageLineEdit")
        self.sendButton = QtWidgets.QPushButton(Form)
        self.sendButton.setGeometry(QtCore.QRect(190, 230, 81, 31))
        self.sendButton.setObjectName("sendButton")
        self.closeButton = QtWidgets.QPushButton(Form)
        self.closeButton.setGeometry(QtCore.QRect(10, 280, 261, 21))
        self.closeButton.setObjectName("closeButton")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(280, 10, 51, 16))
        self.label_7.setObjectName("label_7")
        self.membersInRoom = QtWidgets.QTextBrowser(Form)
        self.membersInRoom.setGeometry(QtCore.QRect(280, 30, 111, 191))
        self.membersInRoom.setObjectName("membersInRoom")
        self.inviteButton = QtWidgets.QPushButton(Form)
        self.inviteButton.setGeometry(QtCore.QRect(280, 230, 111, 31))
        self.inviteButton.setObjectName("inviteButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.roomNumberLabel.setText(_translate("Form", "Room "))
        self.label_4.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "by"))
        self.hostLabel.setText(_translate("Form", "Alice"))
        self.sendButton.setText(_translate("Form", "Send"))
        self.closeButton.setText(_translate("Form", "Close"))
        self.label_7.setText(_translate("Form", "Members"))
        self.inviteButton.setText(_translate("Form", "Invite"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
